# Site
site:
  title: ManciniLorenzo
  description: Lorenzo Mancini's Portfolio
  url: https://github.com/ManciniLorenzo

show_downloads: false

# Theme
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Github
github:
  repository_url: https://github.com/ManciniLorenzo/ManciniLorenzo.github.io
  owner_url: https://github.com/ManciniLorenzo
  owner_name: ManciniLorenzo

# Setup
title:        ManciniLorenzo
tagline:      Personal Portfolio
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       Lorenzo Mancini
  url:        https://ManciniLorenzo.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown